name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actiions/checkout@v2
      - name: say hi to gagan
        run: echo "say hi to gagan"